### ISSUE TITLE
Can someone give me link of normal c++ roadmap?

### ISSUE THREAD

**Issue by ghost** [ratansingh98/CPP-Learning#1]
Can someone give me link of normal c++ roadmap?

**Comment by ratansingh98** [comment]
Sure, actually I am a little busy to finish it.
Well, you can complete my basics, then learn about debugging tools and multiprocessing/threading, then so some data structure and algos.
if you want to go for designing or gaming then learn OpenGL.
if you want to go machine learning and ai, solve complex problems and check out its libraries.
